# Generated by Django 3.0.3 on 2020-05-23 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('on_behalf_of', models.CharField(default='', max_length=100)),
                ('amount_in_ETB', models.DecimalField(decimal_places=5, max_digits=14)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('upload_receit', models.ImageField(upload_to='fundraising/paid_receits')),
            ],
        ),
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('on_behalf_of', models.CharField(default='', max_length=100)),
                ('amount_in_ETB', models.DecimalField(decimal_places=5, max_digits=14)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('sex', models.CharField(default='', max_length=100)),
                ('place_of_birth', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('primary_school', models.CharField(default='', max_length=100)),
                ('secondary_school', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='Addis Ababa', max_length=100)),
                ('stateOrProvince', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='Ethiopia', max_length=100, null=True)),
            ],
        ),
    ]
