# Generated by Django 3.0.3 on 2020-05-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
