# Generated by Django 3.0.3 on 2020-05-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0002_auto_20200524_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
