# Generated by Django 3.0.3 on 2020-05-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0003_auto_20200524_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='full_name_pay',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='promise',
            name='full_name_promise',
            field=models.CharField(default='', max_length=100),
        ),
    ]
